# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-29 06:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productId', models.IntegerField(primary_key=True, serialize=False, verbose_name='理财产品ID')),
                ('productName', models.CharField(max_length=50, verbose_name='理财产品名称')),
                ('productRate', models.FloatField(verbose_name='期望回报率')),
                ('productCloseTime', models.IntegerField(verbose_name='封闭期限')),
                ('minLend', models.IntegerField(default=100, verbose_name='最低出借')),
                ('placementCycle', models.DateTimeField(verbose_name='剩余时间')),
                ('produtBalance', models.FloatField(default=1000000, verbose_name='剩余金额')),
            ],
            options={
                'verbose_name': '理财产品模型',
                'verbose_name_plural': '理财产品模型',
                'db_table': 'wklc_products',
            },
        ),
        migrations.CreateModel(
            name='ProductStyle',
            fields=[
                ('productBigId', models.IntegerField(primary_key=True, serialize=False, verbose_name='理财产品大类ID')),
                ('productBigName', models.CharField(max_length=255, verbose_name='大类名称')),
            ],
            options={
                'verbose_name': '理财产品大类模型',
                'verbose_name_plural': '理财产品大类模型',
                'db_table': 'wklc_productstyles',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='productBig',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ProductStyle', verbose_name='理财产品大类'),
        ),
    ]
