# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-02 06:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_auto_20190701_2116'),
        ('user', '0002_auto_20190701_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=30, verbose_name='用户姓名')),
                ('userPhone', models.CharField(max_length=50, verbose_name='用户电话')),
                ('address', models.CharField(max_length=255, verbose_name='地址')),
                ('detailAddress', models.CharField(max_length=255, verbose_name='详细地址')),
                ('postalCode', models.CharField(max_length=20, verbose_name='邮政编码')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Orders', verbose_name='订单')),
            ],
            options={
                'verbose_name': '用户收货地址',
                'verbose_name_plural': '用户收货地址',
                'db_table': 'wklc_address',
            },
        ),
        migrations.CreateModel(
            name='Default_Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=30, verbose_name='用户姓名')),
                ('userPhone', models.CharField(max_length=50, verbose_name='用户电话')),
                ('address', models.CharField(max_length=255, verbose_name='地址')),
                ('detailAddress', models.CharField(max_length=255, verbose_name='详细地址')),
                ('postalCode', models.CharField(max_length=20, verbose_name='邮政编码')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户默认收货地址',
                'verbose_name_plural': '用户默认收货地址',
                'db_table': 'wklc_default_address',
            },
        ),
    ]
