# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-29 06:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LendInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lendPurpose', models.CharField(max_length=255, verbose_name='借款用途')),
                ('contractPrice', models.FloatField(verbose_name='合同金额')),
                ('contractRate', models.FloatField(verbose_name='合同利率')),
                ('contractLine', models.IntegerField(verbose_name='合同期限')),
                ('personName', models.CharField(max_length=20, verbose_name='借款人姓名')),
                ('itemName', models.CharField(max_length=50, verbose_name='理财名称')),
                ('itemDetail', models.CharField(max_length=255, verbose_name='理财简介')),
                ('personCode', models.CharField(max_length=50, verbose_name='借款人身份证')),
                ('beginDate', models.CharField(max_length=20, verbose_name='起息日')),
                ('returnStyle', models.CharField(max_length=30, verbose_name='还款方式')),
                ('limitOut', models.BooleanField(verbose_name='是否超限')),
                ('returnProtect', models.CharField(max_length=255, verbose_name='还款保障措施')),
                ('returnFrom', models.CharField(max_length=255, verbose_name='还款来源')),
                ('incomeSources', models.CharField(max_length=255, verbose_name='收入')),
                ('industry', models.CharField(max_length=255, verbose_name='行业')),
                ('hasLoan', models.BooleanField(verbose_name='是否有贷款')),
                ('hasReport', models.BooleanField(verbose_name='征信报告')),
                ('otherLeand', models.BooleanField(verbose_name='其他平台贷款')),
                ('otherLeandPrice', models.FloatField(verbose_name='其他平台贷款金额')),
                ('productNameEve', models.CharField(max_length=255, verbose_name='产品金额')),
                ('beOverdueTimes', models.IntegerField(verbose_name='逾期次数')),
                ('beOverduePrice', models.FloatField(verbose_name='逾期总金额')),
                ('beOverrules', models.CharField(max_length=255, verbose_name='逾期利息')),
            ],
            options={
                'verbose_name': '借款信息披漏',
                'verbose_name_plural': '借款信息披漏',
                'db_table': 'wklc_lendinfo',
            },
        ),
        migrations.CreateModel(
            name='LendRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lendUserTel', models.CharField(max_length=50, verbose_name='出借人电话')),
                ('lendMoney', models.FloatField(verbose_name='出借金额')),
                ('lendTime', models.DateTimeField(auto_now=True, verbose_name='出借时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product', verbose_name='理财产品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='用户')),
            ],
            options={
                'verbose_name': '出借记录模型',
                'verbose_name_plural': '出借记录模型',
                'db_table': 'wklc_lendrecords',
            },
        ),
    ]
