# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-01 13:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lends', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lendinfo',
            options={'verbose_name': '出借信息披漏', 'verbose_name_plural': '出借信息披漏'},
        ),
        migrations.AlterModelOptions(
            name='lendrecord',
            options={'verbose_name': '出借记录', 'verbose_name_plural': '出借记录'},
        ),
    ]
