# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-29 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userGrade', models.CharField(max_length=255, verbose_name='用户会员等级')),
                ('equity', models.CharField(max_length=255, verbose_name='解锁权益')),
                ('canLend', models.FloatField(verbose_name='可借出金额')),
            ],
            options={
                'verbose_name': '会员等级模型',
                'verbose_name_plural': '会员等级模型',
                'db_table': 'wklc_members',
            },
        ),
    ]
