# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-29 06:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('goodsId', models.IntegerField(primary_key=True, serialize=False, verbose_name='商品ID')),
                ('goodsName', models.CharField(max_length=255, verbose_name='商品名称')),
                ('isHot', models.BooleanField(default=False, verbose_name='是否热卖')),
                ('isRecommend', models.BooleanField(default=False, verbose_name='是否推荐')),
                ('littlePic', models.CharField(max_length=500, verbose_name='图片地址')),
                ('urplussNum', models.IntegerField(default=100, verbose_name='剩余商品数量')),
                ('isDiscountFirst', models.BooleanField(default=True, verbose_name='首次购买是否优惠')),
                ('isNew', models.BooleanField(default=False, verbose_name='是否新品')),
                ('isBoutique', models.BooleanField(default=False, verbose_name='是否精品')),
                ('kfCoin', models.IntegerField(verbose_name='所需空粉币')),
                ('fuZuan', models.FloatField(default=0.0, verbose_name='所需富钻')),
                ('goodsDescribe', models.CharField(max_length=255, verbose_name='商品描述')),
                ('goodsSpecification', models.CharField(max_length=255, verbose_name='商品规格')),
                ('goodsDetails', models.CharField(max_length=500, verbose_name='商品参数图片地址')),
            ],
            options={
                'verbose_name': '商品模型',
                'verbose_name_plural': '商品模型',
                'db_table': 'wklc_goods',
            },
        ),
        migrations.CreateModel(
            name='GoodsInfo',
            fields=[
                ('bigid', models.IntegerField(primary_key=True, serialize=False, verbose_name='商品大类ID')),
                ('bigname', models.CharField(max_length=50, verbose_name='商品大类名称')),
            ],
            options={
                'verbose_name': '商品类型模型',
                'verbose_name_plural': '商品类型模型',
                'db_table': 'wklc_goodsinfo',
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='big',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsInfo', verbose_name='商品大类'),
        ),
    ]
