# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-01 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'verbose_name': '商品详情', 'verbose_name_plural': '商品详情'},
        ),
        migrations.AlterModelOptions(
            name='goodsinfo',
            options={'verbose_name': '商品类型', 'verbose_name_plural': '商品类型'},
        ),
        migrations.AddField(
            model_name='goodsinfo',
            name='bigimgurl',
            field=models.CharField(default=None, max_length=255, verbose_name='图片地址'),
        ),
    ]
