# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-29 06:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthAccount', models.FloatField(default=0.0, verbose_name='月账户回报金额')),
                ('sensonAccount', models.FloatField(default=0.0, verbose_name='季账户回报金额')),
                ('yearAccount', models.FloatField(default=0.0, verbose_name='年账户回报金额')),
                ('specialAccount', models.FloatField(default=0.0, verbose_name='特殊账户期望回报')),
                ('virtualPrincipal', models.FloatField(default=0.0, verbose_name='虚拟本金')),
            ],
            options={
                'verbose_name': '用户回报金额模型',
                'verbose_name_plural': '用户回报金额模型',
                'db_table': 'wklc_accounts',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardNum', models.CharField(max_length=255, verbose_name='卡号')),
                ('cardTel', models.CharField(max_length=255, verbose_name='卡预留手机号')),
                ('cardPwd', models.CharField(max_length=255, verbose_name='App支付密码')),
                ('cardMoney', models.FloatField(verbose_name='卡账户余额')),
            ],
            options={
                'verbose_name': '银行卡模型',
                'verbose_name_plural': '银行卡模型',
                'db_table': 'wklc_cards',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=20, verbose_name='用户姓名')),
                ('userTel', models.CharField(max_length=20, unique=True, verbose_name='用户电话')),
                ('password', models.CharField(max_length=256, verbose_name='用户密码')),
                ('totalMoney', models.FloatField(default=5000.0, verbose_name='总资产')),
                ('yersterdayReturn', models.FloatField(verbose_name='昨日期望回报')),
                ('totalReturn', models.FloatField(verbose_name='累计期望回报')),
                ('userKfCoin', models.IntegerField(default=500000, verbose_name='空粉币')),
                ('userfuZuan', models.FloatField(default=0.0, verbose_name='富钻')),
                ('zyMoney', models.FloatField(verbose_name='自有本金')),
                ('xyMoney', models.FloatField(verbose_name='虚有本金')),
                ('is_Verify', models.BooleanField(default=False, verbose_name='是否验证')),
                ('userGrade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Members', verbose_name='会员等级')),
            ],
            options={
                'verbose_name': '用户模型',
                'verbose_name_plural': '用户模型',
                'db_table': 'wklc_users',
            },
        ),
        migrations.CreateModel(
            name='User_Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Card', verbose_name='银行卡')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户卡关联模型',
                'verbose_name_plural': '用户卡关联模型',
                'db_table': 'wklc_user_card',
            },
        ),
        migrations.CreateModel(
            name='User_Verify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户验证关联模型',
                'verbose_name_plural': '用户验证关联模型',
                'db_table': 'wklc_user_verify',
            },
        ),
        migrations.CreateModel(
            name='Verify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=20, verbose_name='用户姓名')),
                ('userCard', models.CharField(max_length=30, verbose_name='用户身份证')),
            ],
            options={
                'verbose_name': '身份验证模型',
                'verbose_name_plural': '身份验证模型',
                'db_table': 'wklc_verify',
            },
        ),
        migrations.AddField(
            model_name='user_verify',
            name='verify',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Verify', verbose_name='验证'),
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='用户'),
        ),
    ]
